Numpy

# numpy its a multidimensional
array library.i.e u can store all sort of data.like 1-d,2-d,n-d;

In [4]:
import numpy as np

In [5]:
a= np.array([1,2,3],dtype="int16")

In [6]:
b=np.array([[1.0,2.0,3.0,5.8],[2.1,3,4.2,4.5]])
print("two dimensional array:",a)

two dimensional array: [1 2 3]


In [7]:
print("dimension of a:",a.ndim)
print("dimension of b:",b.ndim)

dimension of a: 1
dimension of b: 2


In [8]:
print("shape of a :",a.shape)

shape of a : (3,)


In [9]:
print("shape of b :",b.shape)

shape of b : (2, 4)


In [10]:
print("a type is :",a.dtype)


a type is : int16


In [11]:
print("size of a :",a.size)

size of a : 3


In [12]:
print("a item size :",a.itemsize) # size of single element in the array .i,e in bytes;
print("total size is a:",a.size*a.itemsize)

a item size : 2
total size is a: 6


In [13]:
#Get specific element [row,column] -ve index is possible similar to list;
b[1,2]

np.float64(4.2)

In [14]:
#Get specific row [row,:]#we use slicing(:) operation
print("row :",b[1,0:1]);


row : [2.1]


In [15]:
#Get specific column[:,column]
print("column :",b[:,1])

column : [2. 3.]


In [16]:
#Getting a little more fancy [starindex:endindex:steps]
print("subset of specific row",b[1,1::2])

subset of specific row [3.  4.5]


In [17]:
#change element
b[1,2]=8
print(b)

b[:,2]=[9,4]
b

[[1.  2.  3.  5.8]
 [2.1 3.  8.  4.5]]


array([[1. , 2. , 9. , 5.8],
       [2.1, 3. , 4. , 4.5]])

# 3-d Example 

In [1]:
import numpy as np

In [2]:
c=np.array([[[1,2],[2,3]],[[3,4],[4,5]]])

In [3]:
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [4]:
type(c)

numpy.ndarray

In [5]:
c.ndim

3

In [6]:
c.shape

(2, 2, 2)

In [7]:
c.size

8

## calculate the memory space took for c numpy array

In [9]:
c.itemsize

8

In [10]:
c.dtype

dtype('int64')

In [11]:
c.itemsize*c.size

64

In [15]:
# get specifice element(work out side in )
print("specified element is :",c[0,1,1])

specified element is : 3


In [18]:
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]]])

In [19]:
c[1,1,1]=100
c

array([[[  1,   2],
        [  2,   3]],

       [[  3,   4],
        [  4, 100]]])

# intilizing different types of array

In [22]:
zm = np.zeros((3,4),dtype=int)

In [23]:
zm

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
zm.ndim

2

In [25]:
zm.shape

(3, 4)

All 1's matrix

In [26]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
 ones= np.ones((3,3),dtype="int16")

In [29]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [36]:
ones[1,1]=50
ones.shape

(3, 3)

In [37]:
ones[1,1]=50
ones

array([[ 1,  1,  1],
       [ 1, 50,  1],
       [ 1, 50, 50]], dtype=int16)

In [39]:
m50 = np.full((4,5),50,dtype="float")

# reuse the already existing array and assign one value to each element

In [41]:
np.full_like(m50,100,dtype="float" )

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

# random matrix

In [42]:
np.random.random_sample((2,3))

array([[0.36763615, 0.48547157, 0.51451573],
       [0.92365614, 0.36551838, 0.80498772]])

In [43]:
np.random.rand(2,4)

array([[0.18985775, 0.62507123, 0.20510395, 0.82333906],
       [0.32412814, 0.19931868, 0.54275393, 0.10835462]])

In [44]:
np.random.randint(2,9,size=(3,3))

array([[5, 4, 8],
       [2, 7, 4],
       [5, 7, 6]], dtype=int32)

In [46]:
# generate identity matrix only one argument bcoz identity matrix is a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])